import { Metadata } from "next";
import Navigation from "../components/navigation";


export const metadata: Metadata = {
  title: {
    template: '%s | Next Movie',
    default: "Next Movie"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <main>
            <Navigation />
          {children}
        </main>
      </body>
    </html>
  )
}
